# -*- coding: utf-8 -*-
from __future__ import annotations
import hashlib,json,sqlite3,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DEFAULT_DB=ROOT/'ki_memory.sqlite3'
LATEST='modern_gap_phase5f_shadow_observation_v2_latest'; HISTORY='modern_gap_phase5f_shadow_observation_v2_history'; CYCLES='modern_gap_phase5f_shadow_observation_v2_cycles'; STATE='modern_gap_phase5f_shadow_observation_v2_state'
SCHEMA_TABLES={
LATEST:['stable_observation_key','shadow_key','hypothesis_id','latest_source_updated_at','latest_source_fingerprint','latest_projection_fingerprint','center_chunk_id','target_chunk_ids','target_count','projected_window_strategy','projected_window_radius','projected_action','expected_gain','closure_delta','overlap_score','read_no_candidate_rate','projected_effectiveness','neuromodulators','source_default_path','real_outcome_observation_available','observation_ready','productive_gap_id','productive_write','first_seen_at','last_seen_at','version_count','details'],
HISTORY:['version_id','stable_observation_key','shadow_key','hypothesis_id','source_updated_at','source_fingerprint','projection_fingerprint','center_chunk_id','target_chunk_ids','target_count','projected_window_strategy','projected_window_radius','projected_action','expected_gain','closure_delta','overlap_score','read_no_candidate_rate','projected_effectiveness','neuromodulators','source_default_path','real_outcome_observation_available','observation_ready','productive_gap_id','productive_write','change_kind','previous_version_id','created_at','details'],
CYCLES:['id','v1_source_rows_seen','v1_creates','v1_updates','v2_latest_inserts','v2_latest_updates','v2_version_inserts','v2_identical_retries','v1_v2_input_count_match','productive_counts_unchanged','details','created_at'],
STATE:['key','value']}
def _q(n):return '"'+str(n).replace('"','""')+'"'
def _con(obj=None):
    p=Path(obj) if isinstance(obj,(str,Path)) else DEFAULT_DB;c=sqlite3.connect(str(p),timeout=120);c.row_factory=sqlite3.Row;return c
def _canon(v):return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=True)
def _hash(v):return hashlib.sha256(_canon(v).encode('utf-8')).hexdigest()
def stable_key(shadow_key,hypothesis_id):return 'stable-shadow-observation:'+hashlib.sha256((str(shadow_key)+'|'+str(int(hypothesis_id))).encode('utf-8')).hexdigest()
def fingerprints(item):
    source={'shadow_key':item.get('shadow_key'),'hypothesis_id':int(item.get('hypothesis_id') or 0),'source_updated_at':int(item.get('source_updated_at') or 0),'center_chunk_id':item.get('center_chunk_id'),'neuromodulators':item.get('neuromodulators') or {}}
    projection={'target_chunk_ids':item.get('target_chunk_ids') or [],'target_count':int(item.get('target_count') or 0),'strategy':item.get('projected_window_strategy'),'radius':item.get('projected_window_radius'),'action':item.get('projected_action'),'expected_gain':item.get('expected_gain'),'closure_delta':item.get('closure_delta'),'overlap_score':item.get('overlap_score'),'read_no_candidate_rate':item.get('read_no_candidate_rate'),'projected_effectiveness':item.get('projected_effectiveness')}
    return _hash(source),_hash(projection)
def ensure_schema(obj=None):
    c=_con(obj)
    try:
        c.execute("CREATE TABLE IF NOT EXISTS "+LATEST+"(stable_observation_key TEXT PRIMARY KEY,shadow_key TEXT NOT NULL,hypothesis_id INTEGER NOT NULL,latest_source_updated_at INTEGER NOT NULL,latest_source_fingerprint TEXT NOT NULL,latest_projection_fingerprint TEXT NOT NULL,center_chunk_id INTEGER,target_chunk_ids TEXT NOT NULL DEFAULT '[]',target_count INTEGER NOT NULL DEFAULT 0,projected_window_strategy TEXT,projected_window_radius INTEGER,projected_action TEXT,expected_gain REAL,closure_delta REAL,overlap_score REAL,read_no_candidate_rate REAL,projected_effectiveness REAL,neuromodulators TEXT NOT NULL DEFAULT '{}',source_default_path INTEGER NOT NULL DEFAULT 1,real_outcome_observation_available INTEGER NOT NULL DEFAULT 0,observation_ready INTEGER NOT NULL DEFAULT 0,productive_gap_id INTEGER,productive_write INTEGER NOT NULL DEFAULT 0,first_seen_at INTEGER NOT NULL,last_seen_at INTEGER NOT NULL,version_count INTEGER NOT NULL DEFAULT 1,details TEXT NOT NULL DEFAULT '{}',UNIQUE(shadow_key,hypothesis_id))")
        c.execute("CREATE TABLE IF NOT EXISTS "+HISTORY+"(version_id INTEGER PRIMARY KEY AUTOINCREMENT,stable_observation_key TEXT NOT NULL,shadow_key TEXT NOT NULL,hypothesis_id INTEGER NOT NULL,source_updated_at INTEGER NOT NULL,source_fingerprint TEXT NOT NULL,projection_fingerprint TEXT NOT NULL,center_chunk_id INTEGER,target_chunk_ids TEXT NOT NULL DEFAULT '[]',target_count INTEGER NOT NULL DEFAULT 0,projected_window_strategy TEXT,projected_window_radius INTEGER,projected_action TEXT,expected_gain REAL,closure_delta REAL,overlap_score REAL,read_no_candidate_rate REAL,projected_effectiveness REAL,neuromodulators TEXT NOT NULL DEFAULT '{}',source_default_path INTEGER NOT NULL DEFAULT 1,real_outcome_observation_available INTEGER NOT NULL DEFAULT 0,observation_ready INTEGER NOT NULL DEFAULT 0,productive_gap_id INTEGER,productive_write INTEGER NOT NULL DEFAULT 0,change_kind TEXT NOT NULL,previous_version_id INTEGER,created_at INTEGER NOT NULL,details TEXT NOT NULL DEFAULT '{}',UNIQUE(stable_observation_key,source_fingerprint,projection_fingerprint,real_outcome_observation_available,observation_ready))")
        c.execute("CREATE TABLE IF NOT EXISTS "+CYCLES+"(id INTEGER PRIMARY KEY AUTOINCREMENT,v1_source_rows_seen INTEGER NOT NULL DEFAULT 0,v1_creates INTEGER NOT NULL DEFAULT 0,v1_updates INTEGER NOT NULL DEFAULT 0,v2_latest_inserts INTEGER NOT NULL DEFAULT 0,v2_latest_updates INTEGER NOT NULL DEFAULT 0,v2_version_inserts INTEGER NOT NULL DEFAULT 0,v2_identical_retries INTEGER NOT NULL DEFAULT 0,v1_v2_input_count_match INTEGER NOT NULL DEFAULT 0,productive_counts_unchanged INTEGER NOT NULL DEFAULT 0,details TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)")
        c.execute("CREATE TABLE IF NOT EXISTS "+STATE+"(key TEXT PRIMARY KEY,value TEXT)")
        c.execute('CREATE INDEX IF NOT EXISTS idx_v2_hist_stable ON '+HISTORY+'(stable_observation_key,version_id)');c.execute('CREATE INDEX IF NOT EXISTS idx_v2_latest_hyp ON '+LATEST+'(hypothesis_id)')
        defaults={'contract_version':'stable_obs_v2_shadow_v1','mode':'shadow_dual_write','backfill':'disabled','migration':'disabled','reader_switch':'disabled','v1_delete':'disabled','observation_ready':'false','productive_writes':'disabled'}
        for k,v in defaults.items():c.execute('INSERT OR IGNORE INTO '+STATE+'(key,value) VALUES(?,?)',(k,str(v)))
        _self_check_schema(c);c.commit();return {'overall':True,'tables':list(SCHEMA_TABLES)}
    finally:c.close()
def _self_check_schema(c):
    missing={}
    for table,want in SCHEMA_TABLES.items():
        live=[str(r[1]) for r in c.execute('PRAGMA table_info('+_q(table)+')')];m=[x for x in want if x not in live]
        if m:missing[table]=m
    if missing:raise RuntimeError('V2 schema missing '+repr(missing))
    return {'overall':True}
def record_dual_write(con,item,now=None):
    _self_check_schema(con);now=int(now or time.time());sk=stable_key(item['shadow_key'],item['hypothesis_id']);sf,pf=fingerprints(item);prev=con.execute('SELECT * FROM '+LATEST+' WHERE stable_observation_key=?',(sk,)).fetchone()
    if prev and prev['latest_source_fingerprint']==sf and prev['latest_projection_fingerprint']==pf:return {'latest_insert':0,'latest_update':0,'version_insert':0,'identical_retry':1,'change_kind':'technical_retry_or_identical_state'}
    if prev is None:kind='initial_observation';previous_id=None
    else:
        sc=prev['latest_source_fingerprint']!=sf;pc=prev['latest_projection_fingerprint']!=pf;kind='source_and_projection_change' if sc and pc else ('source_state_change' if sc else 'projection_change');p=con.execute('SELECT version_id FROM '+HISTORY+' WHERE stable_observation_key=? ORDER BY version_id DESC LIMIT 1',(sk,)).fetchone();previous_id=int(p[0]) if p else None
    vals=(sk,item['shadow_key'],int(item['hypothesis_id']),int(item.get('source_updated_at') or 0),sf,pf,item.get('center_chunk_id'),_canon(item.get('target_chunk_ids') or []),int(item.get('target_count') or 0),item.get('projected_window_strategy'),item.get('projected_window_radius'),item.get('projected_action'),item.get('expected_gain'),item.get('closure_delta'),item.get('overlap_score'),item.get('read_no_candidate_rate'),item.get('projected_effectiveness'),_canon(item.get('neuromodulators') or {}),1,0,0,None,0,kind,previous_id,now,_canon({'contract':'stable_obs_v2_shadow_v1','real_outcome_source':'unavailable','observation_ready_gate':'closed'}))
    con.execute('INSERT INTO '+HISTORY+'(stable_observation_key,shadow_key,hypothesis_id,source_updated_at,source_fingerprint,projection_fingerprint,center_chunk_id,target_chunk_ids,target_count,projected_window_strategy,projected_window_radius,projected_action,expected_gain,closure_delta,overlap_score,read_no_candidate_rate,projected_effectiveness,neuromodulators,source_default_path,real_outcome_observation_available,observation_ready,productive_gap_id,productive_write,change_kind,previous_version_id,created_at,details) VALUES('+','.join('?' for _ in vals)+')',vals)
    common=(int(item.get('source_updated_at') or 0),sf,pf,item.get('center_chunk_id'),_canon(item.get('target_chunk_ids') or []),int(item.get('target_count') or 0),item.get('projected_window_strategy'),item.get('projected_window_radius'),item.get('projected_action'),item.get('expected_gain'),item.get('closure_delta'),item.get('overlap_score'),item.get('read_no_candidate_rate'),item.get('projected_effectiveness'),_canon(item.get('neuromodulators') or {}),now)
    if prev is None:
        con.execute('INSERT INTO '+LATEST+'(stable_observation_key,shadow_key,hypothesis_id,latest_source_updated_at,latest_source_fingerprint,latest_projection_fingerprint,center_chunk_id,target_chunk_ids,target_count,projected_window_strategy,projected_window_radius,projected_action,expected_gain,closure_delta,overlap_score,read_no_candidate_rate,projected_effectiveness,neuromodulators,source_default_path,real_outcome_observation_available,observation_ready,productive_gap_id,productive_write,first_seen_at,last_seen_at,version_count,details) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(sk,item['shadow_key'],int(item['hypothesis_id']))+common[:-1]+(1,0,0,None,0,now,now,1,_canon({'contract':'stable_obs_v2_shadow_v1'})));return {'latest_insert':1,'latest_update':0,'version_insert':1,'identical_retry':0,'change_kind':kind}
    con.execute('UPDATE '+LATEST+' SET latest_source_updated_at=?,latest_source_fingerprint=?,latest_projection_fingerprint=?,center_chunk_id=?,target_chunk_ids=?,target_count=?,projected_window_strategy=?,projected_window_radius=?,projected_action=?,expected_gain=?,closure_delta=?,overlap_score=?,read_no_candidate_rate=?,projected_effectiveness=?,neuromodulators=?,last_seen_at=?,version_count=version_count+1 WHERE stable_observation_key=?',common+(sk,));return {'latest_insert':0,'latest_update':1,'version_insert':1,'identical_retry':0,'change_kind':kind}
def record_cycle(con,v1_seen,v1_created,v1_updated,stats,productive_unchanged,now=None):
    now=int(now or time.time());match=1 if int(v1_seen)==int(stats.get('inputs',0)) else 0
    con.execute('INSERT INTO '+CYCLES+'(v1_source_rows_seen,v1_creates,v1_updates,v2_latest_inserts,v2_latest_updates,v2_version_inserts,v2_identical_retries,v1_v2_input_count_match,productive_counts_unchanged,details,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',(int(v1_seen),int(v1_created),int(v1_updated),int(stats.get('latest_insert',0)),int(stats.get('latest_update',0)),int(stats.get('version_insert',0)),int(stats.get('identical_retry',0)),match,1 if productive_unchanged else 0,_canon({'contract':'stable_obs_v2_shadow_v1'}),now))
    for k,v in {'last_v1_inputs':v1_seen,'last_v2_inputs':stats.get('inputs',0),'last_input_count_match':match,'last_productive_counts_unchanged':1 if productive_unchanged else 0}.items():con.execute('INSERT INTO '+STATE+'(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',(str(k),str(v)))
    return {'input_count_match':bool(match),'productive_counts_unchanged':bool(productive_unchanged)}
